const path = require('path');
const fs = require('fs/promises');
const Jimp = require('jimp');

async function run() {
  const outputDir = path.join(__dirname, '..', 'artifacts');
  await fs.mkdir(outputDir, { recursive: true });

  const image = await new Jimp(800, 400, 0xffffffff);
  const font = await Jimp.loadFont(Jimp.FONT_SANS_32_BLACK);

  image.print(
    font,
    0,
    120,
    {
      text: 'DevOps E2E Website',
      alignmentX: Jimp.HORIZONTAL_ALIGN_CENTER,
      alignmentY: Jimp.VERTICAL_ALIGN_MIDDLE
    },
    800,
    80
  );

  image.print(
    font,
    0,
    240,
    {
      text: 'Generated by GitHub Actions',
      alignmentX: Jimp.HORIZONTAL_ALIGN_CENTER,
      alignmentY: Jimp.VERTICAL_ALIGN_MIDDLE
    },
    800,
    80
  );

  const outputPath = path.join(outputDir, 'site-image.png');
  await image.writeAsync(outputPath);
  console.log(`Image generated: ${outputPath}`);
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
